### PR TITLE
Wicket 6

### PR DESCRIPTION
**Pull request by papegaaij**

### CODE REVIEW

**Comment by hielkehoeve** [comment]
better late than never :)

**Comment by Otah** [comment]
Is there any idea, when the pull will be done? There is still no "official" branch for Wicket 6, do I understand it well? Or am I completely confused and there is a merge somewhere?
We use this library and we want to stay maven-powered (download of papegaaij's sources is not very suitable option for us), but there is no way at this moment (or is it?) And the current version does not work with Wicket 6 at all.

**Comment by hielkehoeve** [comment]
We are working on wicket 6 versions of a number of libraries as well as
Wicket 6 itself, in our spare time.  Due to the extensive rework of Wicket
we have waited a while before finishing the versions. This library is,
unfortunately, one of the last ones.

Feel free to fork and do some of the work for us.

A snapshot will be released to Sonatype soon.
On Jun 5, 2012 1:49 PM, "Otah" <
reply@reply.github.com>
wrote:

**Comment by Otah** [comment]
I have done a fork of @papegaaij 's fork and tried to remove the dependency on whole WiQuery from the Wicket-6 branch. It was very easy - the main change can be found at:
https://github.com/Otah/wiquery-highcharts/commit/be1e9b8faa9f3777657ffa65a8edbd552ad79661#diff-2

To summarize the commit, the only part (except of the test page) dependent on WiQuery is the main class WHighChart. In this file, the only usage of WiQuery was returning a JsStatement from the statement() method. But I am asking why? It was not related to any functionality of JsStatement, it has only appended a "raw" JavaScript string to an empty builder. And this "functionality" was causing the only reason, why the Wicket 6 version of this project has to be dependent on WiQuery.

I definitely understand, this project's content is WiQuery-Highcharts integration, but from my point of view, there are two lot-more important aspects, which build the core of this project:
1. the "builder pattern" for writing HighCharts data in Java
2. the integration with Apache Wicket

So why to force the usage of WiQuery in this case? Due to the nature of its usage, the user of this project is forced to use something, which is really not necessary at all. Why to wrap the single line of JavaScript of Highchart init by JsStatement? If the user wants this functionality, he can include WiQuery and wrap it. But again - why to force it?

Btw: Did you consider the separation of the two above-mentioned parts? Someone who is not using Wicket but any Java code can be also interested in the Java Highcharts builder.

Thank you. If this comment should be moved somewhere, please, let me know. I am quite new at GitHub...

**Pull request closed without merging**
